package com.github.cyberryan1.netuno.models;

import com.github.cyberryan1.netuno.api.exceptions.IncompleteReportException;
import com.github.cyberryan1.netuno.api.models.ApiReport;

import java.util.List;
import java.util.UUID;

public class NetunoReport implements ApiReport {
    
    // if the ID of a report is set to this, then its ID still 
    //      needs to be generated by the database 
    public static final int DEFAULT_ID = -1;
    // this is what is used to separate the reasons in the 
    //      database column
    public static final String REASON_DELIMITER = "@@@";
    
    private int id;
    private final UUID uuid;
    private final List<String> reasons;
    private final UUID reportAuthorUuid;
    private final long reportDate;

    /**
     * Creates a new NetunoReport with all fields specified,
     * except for the ID. The ID is set to {@link #DEFAULT_ID}
     *
     * @param player       The UUID of the player that was
     *                     reported
     * @param reasons      List of reasons why this player was
     *                     reported
     * @param reportAuthor The UUID of the player that made the
     *                     report
     * @param reportDate   The timestamp of when this report was
     *                     made
     */
    public NetunoReport( UUID player, List<String> reasons, UUID reportAuthor, long reportDate ) {
        this( DEFAULT_ID, player, reasons, reportAuthor, reportDate );
    }
    

    /**
     * Creates a new NetunoReport with all fields specified
     *
     * @param id           The unique identifier of this report,
     *                     or {@link #DEFAULT_ID} if not yet
     *                     generated
     * @param player       The UUID of the player that was
     *                     reported
     * @param reasons      List of reasons why this player was
     *                     reported
     * @param reportAuthor The UUID of the player that made the
     *                     report
     * @param reportDate   The timestamp of when this report was
     *                     made
     */
    public NetunoReport( int id, UUID player, List<String> reasons, UUID reportAuthor, long reportDate ) {
        this.id = id;
        this.uuid = player;
        this.reasons = reasons;
        this.reportAuthorUuid = reportAuthor;
        this.reportDate = reportDate;
    }

    /**
     * Similar to {@link #NetunoReport(UUID, List, UUID, long)},
     * but parses the reasons string into a list of reasons. Each
     * reason should be separated by {@link #REASON_DELIMITER}
     *
     * @param id           The unique identifier of this report,
     *                     or {@link #DEFAULT_ID} if not yet
     *                     generated
     * @param player       The UUID of the player that was
     *                     reported
     * @param reasons      List of reasons why this player was
     *                     reported, separated by 
     *                     {@link #REASON_DELIMITER}
     * @param reportAuthor The UUID of the player that made the
     *                     report
     * @param reportDate   The timestamp of when this report was
     *                     made
     */
    public NetunoReport( int id, UUID player, String reasons, UUID reportAuthor, long reportDate ) {
        this( id, player, List.of( reasons.split( REASON_DELIMITER ) ), reportAuthor, reportDate );
    }

    /**
     * Gets the unique identifier of this report
     *
     * @return The ID of this report
     */
    @Override
    public int getId() {
        return id;
    }

    /**
     * Sets the unique identifier of this report
     *
     * @param id The new ID for this report
     */
    public void setId( int id ) {
        this.id = id;
    }

    /**
     * Gets the UUID of the reported player
     *
     * @return The UUID of the player that was reported
     */
    @Override
    public UUID getPlayer() {
        return uuid;
    }

    /**
     * Gets the reasons for this report
     *
     * @return List of reasons why this player was reported
     */
    @Override
    public List<String> getReasons() {
        return reasons;
    }

    /**
     * Gets all reasons concatenated into a single string, with
     * each reason separated by {@link #REASON_DELIMITER}
     *
     * @return String containing all reasons, separated by
     *         {@link #REASON_DELIMITER}
     */
    public String getReasonsString() {
        StringBuilder sb = new StringBuilder();
        for ( String reason : reasons ) {
            sb.append( reason ).append( REASON_DELIMITER );
        }
        return sb.toString();
    }

    /**
     * Gets the UUID of the player who made this report
     *
     * @return The UUID of the player that made the report
     */
    @Override
    public UUID getReportAuthor() {
        return reportAuthorUuid;
    }

    /**
     * Gets the timestamp of when this report was made
     *
     * @return Timestamp of when this report was made
     */
    @Override
    public long getReportDate() {
        return reportDate;
    }


    /**
     * Validates all fields of this report to ensure they are
     * properly set and contain valid values. This method checks
     * that:
     * <ul>
     *     <li>The ID is greater than zero (if requireValidId is true)</li>
     *     <li>The player UUID is not null</li>
     *     <li>The reasons list is not null or empty</li>
     *     <li>The report author UUID is not null</li>
     *     <li>The report date is greater than zero</li>
     *     <li>No reason in the reasons list is null or empty</li>
     *     <li>No reason contains the {@link #REASON_DELIMITER}</li>
     * </ul>
     *
     * @param requireValidId If true, validates that the report
     *                       ID is greater than zero
     * @throws IncompleteReportException If any of the validation
     *                                   checks fail
     */
    public void ensureValid( boolean requireValidId ) {
        if ( requireValidId &&  id <= 0 ) throw new IncompleteReportException( "Report incomplete: Punishment ID must be greater than zero" );
        if ( uuid == null ) throw new IncompleteReportException( "Report incomplete: Player UUID must be specified" );
        if ( reasons == null || reasons.isEmpty() ) throw new IncompleteReportException( "Report incomplete: Reasons must be specified" );
        if ( reportAuthorUuid == null ) throw new IncompleteReportException( "Report incomplete: Report author UUID must be specified" );
        if ( reportDate <= 0 ) throw new IncompleteReportException( "Report incomplete: Report date must be greater than zero" );
        for ( String reason : reasons ) {
            if ( reason == null || reason.isEmpty() ) throw new IncompleteReportException( "Report incomplete: Reasons list contains an empty/null string" );
        }
        for ( String reason : reasons ) {
            if ( reason.contains( REASON_DELIMITER ) ) throw new IncompleteReportException( "Report incomplete: Reason cannot contain '" + REASON_DELIMITER + "'" );
        }
    }
}
