name: Netuno
version: ${project.version}
main: com.github.cyberryan1.netuno.Netuno
api-version: 1.16
softdepend: [ Vault, Skript ]
authors: [ CyberRyan ]
commands:
  netuno:
  warn:
  kick:
  mute:
  unmute:
  ban:
  unban:
  ipinfo:
    aliases: [ipi, ipc, ipcheck, alts]
  ipmute:
  unipmute:
    aliases: [unmuteip]
  ipban:
  unipban:
    aliases: [unbanip]
  history:
  togglesigns:
  clearchat:
  mutechat:
  reports:
  report:
  punish:
    aliases: [pun, p]
  chatslow:
    aliases: [slowchat]